name: Generate ASCII

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        -  name: checkout repo
           uses: actions/checkout@v4

        -  name: Install Cowsay Program
           run: sudo apt-get install cowsay -y

        -  name: Execute Cowsay CMD
           run: cowsay -f elephant "Vote for Vj, I AM TVK ELEPHANTTTT" >> elephant.txt

        -  name: Finding file
           run: grep -i "elephant" elephant.txt

        -  name: Read file
           run: cat elephant.txt

        -  name: list repo files
           run: ls -lrta
           