name: Generate ASCII

on: push

jobs:
    Build_job_1:
        runs-on: ubuntu-latest
        steps:
        -  name: Install Cowsay Program
           run: sudo apt-get install cowsay -y
 
        -  name: Execute Cowsay CMD
           run: cowsay -f elephant "Vote for Vj, I AM TVK ELEPHANTTTT" >> elephant.txt
        
        -  name: Sleep for 30 sec
           run: sleep 30
    
    test_job:
        runs-on: ubuntu-latest
        steps:
        -  name: Sleep for 10 sec
           run: sleep 10

        -  name: Finding file
           run: grep -i "elephant" elephant.txt

    Deploy_job:
        runs-on: ubuntu-latest
        steps:
        -  name: Read file
           run: cat elephant.txt
           
        -  name: Deploy
           run: echo deploying......
            

       