name: Generate ASCII

on: push

jobs:
    Build_job_1:
        runs-on: ubuntu-latest
        steps:
        -  name: Install Cowsay Program
           run: sudo apt-get install cowsay -y
 
        -  name: Execute Cowsay CMD
           run: cowsay -f elephant "Vote for Vj, I AM TVK ELEPHANTTTT" >> elephant.txt
        
        -  name: Upload a file
           uses: actions/upload-artifact@v4
           with:
             name: elephant-file
             path: elephant.txt
           
    
    test_job:
        needs: Build_job_1
        runs-on: ubuntu-latest
        steps:
        -  name: dowload a file
           uses: actions/download-artifact@v4
           with:
             name: elephant-file

        -  name: Finding file
           run: grep -i "elephant" elephant.txt

    Deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:

        -  name: dowload a file
           uses: actions/download-artifact@v4
           with:
             name: elephant-file
             
        -  name: Read file
           run: cat elephant.txt
           
        -  name: Deploy
           run: echo deploying......
            

       