name: Workflow CI 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        -  name: checkout repo
           uses: actions/checkout@v4

        -  name: Command Execution
           run: | #Multi-line command execution
            echo "My first GA job"
            ls -lrta
            cat README.md

        -  name: Generate ASCII artwork
           run: cowsay -f elephant "Vote for Vj, I AM TVK ELEPHANTTTT" >> elephant.txt

         

       #-  name: List files
       #   run: ls

       #-  name: Read file
       #  run: cat README.md
