name: Workflow CI 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        -  name: Welcome!
           run: echo "My first GA job"

        -  name: List files
           run: lrth -a 

        -  name: Read file
           run: cat README.md