name: Varaibles

on: [push]

#Variables at workflow level
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: Sabari
  IMAGE_NAME: github-actions-nginx
  DOCKER_PASSWORD: 53curePassword

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker Login
        run: echo docker login--username $DOCKER USERNAME --password-$DOCKER_PASSWORD

      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


